### ISSUE TITLE
Put placeholder image when either side's video is turned off

### ISSUE THREAD

**Issue by bidyut-majumdar** [MaroofTech/vlcc-web-issue-tracker#233]
This issue is quite linked with #204  ,  when video is off on any side (customer or expert) its completely gone, please put placeholder image (ex: customer's or expert's image) on that place instead of completely blank.

**Comment by kanishkavayuz** [comment]
@bidyut-majumdar  ill share my thought on the following cases
1. For local stream video call space I can handle at my end  to cover up with illustration(Profile image, for the customer, and Static image for the Expert(Since Expert doesn't have an image )), But I need HTML/CSS code for the video of which can cover up the video space
![image](https://user-images.githubusercontent.com/78138350/155932508-069bc662-02fd-408c-845d-d9afdac7f73b.png)

2. For remote Stream I need the help of the @MaroofTech  for handling things i have recognized event handler in EnableX(when the remote video is getting called,), I need help of @MaroofTech sir to bind the static image for the remote video
![image](https://user-images.githubusercontent.com/78138350/155932729-5cf91582-d371-4a2d-a438-0fdcfa1324ab.png)

**Comment by bidyut-majumdar** [comment]
!IMPORTANT

@kanishkavayuz discuss with me on next morning must .

**Comment by bidyut-majumdar** [comment]
@kanishkavayuz  Get me update on any solution for this by today morning .

**Comment by MaroofTech** [comment]
@bidyut-majumdar we have imlemented solution but its not working, there is CSS dependency for this pointer need to discuss same need some help regarding CSS
